package com.github.anhem.testpopulator.model.java.constructor;

import com.github.anhem.testpopulator.model.java.ArbitraryEnum;
import lombok.EqualsAndHashCode;
import lombok.Getter;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.*;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.nio.file.Path;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

@Getter
@EqualsAndHashCode(callSuper = true)
public class AllArgsConstructorExtendsAllArgsConstructorAbstract extends AllArgsConstructorAbstract {

    private final String anotherString;

    public AllArgsConstructorExtendsAllArgsConstructorAbstract(
            String stringValue,
            char primitiveCharacterValue,
            Character characterValue,
            int primitiveIntegerValue,
            Integer integerValue,
            long primitiveLongValue,
            Long longValue,
            double primitiveDoubleValue,
            Double doubleValue,
            boolean primitiveBooleanValue,
            Boolean booleanValue,
            BigDecimal bigDecimal,
            Optional<Integer> optionalInteger,
            Optional<String> optionalString,
            Charset charset,
            Calendar calendar,
            LocalDate localDate,
            LocalDateTime localDateTime,
            ZonedDateTime zonedDateTime,
            Instant instant,
            List<String> listOfStrings,
            List<ArbitraryEnum> listOfEnums,
            Set<String> setOfStrings,
            EnumSet<ArbitraryEnum> enumSet,
            BitSet bitSet,
            Queue<String> queue,
            Deque<String> deque,
            SortedSet<String> sortedSet,
            NavigableSet<String> navigableSet,
            Map<Integer, String> mapOfIntegersToStrings,
            Map<String, Integer> mapOfStringsToIntegers,
            Map<String, ArbitraryEnum> mapOfStringsToEnums,
            EnumMap<ArbitraryEnum, String> enumMap,
            SortedMap<String, Integer> sortedMap,
            NavigableMap<String, Integer> navigableMap,
            ConcurrentMap<String, String> concurrentMap,
            ConcurrentNavigableMap<String, String> concurrentNavigableMap,
            ConcurrentSkipListMap<String, String> concurrentSkipListMap,
            CopyOnWriteArrayList<String> copyOnWriteArrayList,
            CopyOnWriteArraySet<String> copyOnWriteArraySet,
            ConcurrentSkipListSet<String> concurrentSkipListSet,
            TreeMap<String, String> treeMap,
            TreeSet<String> treeSet,
            ArbitraryEnum arbitraryEnum,
            String[] arrayOfStrings,
            byte[] arrayOfBytes,
            char[] arrayOfChars,
            int[] arrayOfInts,
            long[] arrayOfLongs,
            float[] arrayOfFloats,
            double[] arrayOfDoubles,
            short[] arrayOfShorts,
            boolean[] arrayOfBooleans,
            ArrayList<String> arrayList,
            LinkedList<String> linkedList,
            HashMap<String, String> hashMap,
            LinkedHashMap<String, String> linkedHashMap,
            HashSet<String> hashSet,
            LinkedHashSet<String> linkedHashSet,
            Date date,
            Byte byteValue,
            byte primitiveByteValue,
            Short shortValue,
            short primitiveShortValue,
            Float floatValue,
            float primitiveFloatValue,
            LocalTime localTime,
            BigInteger bigInteger,
            OffsetDateTime offsetDateTime,
            OffsetTime offsetTime,
            Duration duration,
            Period period,
            java.sql.Date sqlDate,
            Time sqlTime,
            Timestamp sqlTimestamp,
            Currency currency,
            Locale locale,
            TimeZone timeZone,
            ZoneId zoneId,
            ZoneOffset zoneOffset,
            Year year,
            YearMonth yearMonth,
            MonthDay monthDay,
            Month month,
            DayOfWeek dayOfWeek,
            Map.Entry<String, String> mapEntry,
            Properties properties,
            Hashtable<String, Integer> hashtable,
            Vector<String> vector,
            Map<String, List<String>> nestedMap,
            List<List<String>> nestedList,
            Set<Set<String>> nestedSet,
            Map<String, Map<Integer, String>> nestedMap2,
            Map<String, Optional<String>> mapOfOptionals,
            List<Map.Entry<String, Integer>> listOfEntries,
            Stack<String> stack,
            Integer[] arrayOfIntegerObjects,
            Long[] arrayOfLongObjects,
            Path path,
            URL url,
            URI uri,
            ByteBuffer byteBuffer,
            InetAddress inetAddress,
            Inet4Address inet4Address,
            Inet6Address inet6Address,
            InetSocketAddress inetSocketAddress,
            String anotherString
    ) {
        super(
                stringValue,
                primitiveCharacterValue,
                characterValue,
                primitiveIntegerValue,
                integerValue,
                primitiveLongValue,
                longValue,
                primitiveDoubleValue,
                doubleValue,
                primitiveBooleanValue,
                booleanValue,
                bigDecimal,
                optionalInteger,
                optionalString,
                charset,
                calendar,
                localDate,
                localDateTime,
                zonedDateTime,
                instant,
                listOfStrings,
                listOfEnums,
                setOfStrings,
                enumSet,
                bitSet,
                queue,
                deque,
                sortedSet,
                navigableSet,
                mapOfIntegersToStrings,
                mapOfStringsToIntegers,
                mapOfStringsToEnums,
                enumMap,
                sortedMap,
                navigableMap,
                concurrentMap,
                concurrentNavigableMap,
                concurrentSkipListMap,
                copyOnWriteArrayList,
                copyOnWriteArraySet,
                concurrentSkipListSet,
                treeMap,
                treeSet,
                arbitraryEnum,
                arrayOfStrings,
                arrayOfBytes,
                arrayOfChars,
                arrayOfInts,
                arrayOfLongs,
                arrayOfFloats,
                arrayOfDoubles,
                arrayOfShorts,
                arrayOfBooleans,
                arrayList,
                linkedList,
                hashMap,
                linkedHashMap,
                hashSet,
                linkedHashSet,
                date,
                byteValue,
                primitiveByteValue,
                shortValue,
                primitiveShortValue,
                floatValue,
                primitiveFloatValue,
                localTime,
                bigInteger,
                offsetDateTime,
                offsetTime,
                duration,
                period,
                sqlDate,
                sqlTime,
                sqlTimestamp,
                currency,
                locale,
                timeZone,
                zoneId,
                zoneOffset,
                year,
                yearMonth,
                monthDay,
                month,
                dayOfWeek,
                mapEntry,
                properties,
                hashtable,
                vector,
                nestedMap,
                nestedList,
                nestedSet,
                nestedMap2,
                mapOfOptionals,
                listOfEntries,
                stack,
                arrayOfIntegerObjects,
                arrayOfLongObjects,
                path,
                url,
                uri,
                byteBuffer,
                inetAddress,
                inet4Address,
                inet6Address,
                inetSocketAddress
        );
        this.anotherString = anotherString;
    }
}
