package com.github.anhem.testpopulator.model.java.setter;

import com.github.anhem.testpopulator.model.java.ArbitraryEnum;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.*;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.nio.file.Path;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode
public abstract class PojoAbstract {

    private String stringValue;
    private char primitiveCharacterValue;
    private Character characterValue;
    private int primitiveIntegerValue;
    private Integer integerValue;
    private long primitiveLongValue;
    private Long longValue;
    private double primitiveDoubleValue;
    private Double doubleValue;
    private boolean primitiveBooleanValue;
    private Boolean booleanValue;
    private BigDecimal bigDecimal;
    private Optional<Integer> optionalInteger;
    private Optional<String> optionalString;
    private Charset charset;
    private Calendar calendar;
    private LocalDate localDate;
    private LocalDateTime localDateTime;
    private ZonedDateTime zonedDateTime;
    private Instant instant;
    private List<String> listOfStrings;
    private List<ArbitraryEnum> listOfEnums;
    private Set<String> setOfStrings;
    private EnumSet<ArbitraryEnum> enumSet;
    private BitSet bitSet;
    private Queue<String> queue;
    private Deque<String> deque;
    private SortedSet<String> sortedSet;
    private NavigableSet<String> navigableSet;
    private Map<Integer, String> mapOfIntegersToStrings;
    private Map<String, Integer> mapOfStringsToIntegers;
    private Map<String, ArbitraryEnum> mapOfStringsToEnums;
    private EnumMap<ArbitraryEnum, String> enumMap;
    private SortedMap<String, Integer> sortedMap;
    private NavigableMap<String, Integer> navigableMap;
    private ConcurrentMap<String, String> concurrentMap;
    private ConcurrentNavigableMap<String, String> concurrentNavigableMap;
    private ConcurrentSkipListMap<String, String> concurrentSkipListMap;
    private CopyOnWriteArrayList<String> copyOnWriteArrayList;
    private CopyOnWriteArraySet<String> copyOnWriteArraySet;
    private ConcurrentSkipListSet<String> concurrentSkipListSet;
    private TreeMap<String, String> treeMap;
    private TreeSet<String> treeSet;
    private ArbitraryEnum arbitraryEnum;
    private String[] arrayOfStrings;
    private byte[] arrayOfBytes;
    private char[] arrayOfChars;
    private int[] arrayOfInts;
    private long[] arrayOfLongs;
    private float[] arrayOfFloats;
    private double[] arrayOfDoubles;
    private short[] arrayOfShorts;
    private boolean[] arrayOfBooleans;
    private ArrayList<String> arrayList;
    private LinkedList<String> linkedList;
    private HashMap<String, String> hashMap;
    private LinkedHashMap<String, String> linkedHashMap;
    private HashSet<String> hashSet;
    private LinkedHashSet<String> linkedHashSet;
    private Date date;
    private Byte byteValue;
    private byte primitiveByteValue;
    private Short shortValue;
    private short primitiveShortValue;
    private Float floatValue;
    private float primitiveFloatValue;
    private LocalTime localTime;
    private BigInteger bigInteger;
    private OffsetDateTime offsetDateTime;
    private OffsetTime offsetTime;
    private Duration duration;
    private Period period;
    private java.sql.Date sqlDate;
    private Time sqlTime;
    private Timestamp sqlTimestamp;
    private Currency currency;
    private Locale locale;
    private TimeZone timeZone;
    private ZoneId zoneId;
    private ZoneOffset zoneOffset;
    private Year year;
    private YearMonth yearMonth;
    private MonthDay monthDay;
    private Month month;
    private DayOfWeek dayOfWeek;
    private Map.Entry<String, String> mapEntry;
    private Properties properties;
    private Hashtable<String, Integer> hashtable;
    private Vector<String> vector;
    private Map<String, List<String>> nestedMap;
    private List<List<String>> nestedList;
    private Set<Set<String>> nestedSet;
    private Map<String, Map<Integer, String>> nestedMap2;
    private Map<String, Optional<String>> mapOfOptionals;
    private List<Map.Entry<String, Integer>> listOfEntries;
    private Stack<String> stack;
    private Integer[] arrayOfIntegerObjects;
    private Long[] arrayOfLongObjects;
    private Path path;
    private URL url;
    private URI uri;
    private ByteBuffer byteBuffer;
    private InetAddress inetAddress;
    private Inet4Address inet4Address;
    private Inet6Address inet6Address;
    private InetSocketAddress inetSocketAddress;
    private Map<String, ? extends Integer> mapWithWildcardValue;
    private List<? extends Integer> listWithWildcard;
    private Set<? extends Integer> setWithWildcard;
    private Map<? extends String, ? extends Integer> mapWithWildcardKeyAndValue;
    private Queue<? extends String> queueWithWildcard;
    private Deque<? extends String> dequeWithWildcard;
    private SortedSet<? extends String> sortedSetWithWildcard;
    private NavigableSet<? extends String> navigableSetWithWildcard;
    private SortedMap<? extends String, ? extends Integer> sortedMapWithWildcard;
    private NavigableMap<? extends String, ? extends Integer> navigableMapWithWildcard;
    private ConcurrentMap<? extends String, ? extends String> concurrentMapWithWildcard;
    private ConcurrentNavigableMap<? extends String, ? extends String> concurrentNavigableMapWithWildcard;
    private ConcurrentSkipListMap<? extends String, ? extends String> concurrentSkipListMapWithWildcard;
    private CopyOnWriteArrayList<? extends String> copyOnWriteArrayListWithWildcard;
    private CopyOnWriteArraySet<? extends String> copyOnWriteArraySetWithWildcard;
    private ConcurrentSkipListSet<? extends String> concurrentSkipListSetWithWildcard;
    private TreeMap<? extends String, ? extends String> treeMapWithWildcard;
    private TreeSet<? extends String> treeSetWithWildcard;
    private ArrayList<? extends String> arrayListWithWildcard;
    private LinkedList<? extends String> linkedListWithWildcard;
    private HashMap<? extends String, ? extends String> hashMapWithWildcard;
    private LinkedHashMap<? extends String, ? extends String> linkedHashMapWithWildcard;
    private HashSet<? extends String> hashSetWithWildcard;
    private LinkedHashSet<? extends String> linkedHashSetWithWildcard;
    private Map.Entry<? extends String, ? extends String> mapEntryWithWildcard;
    private Hashtable<? extends String, ? extends Integer> hashtableWithWildcard;
    private Vector<? extends String> vectorWithWildcard;
    private Stack<? extends String> stackWithWildcard;
}
