package com.github.anhem.testpopulator.model.java.field;

import com.github.anhem.testpopulator.model.java.ArbitraryEnum;
import lombok.Getter;

import java.io.File;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.URI;
import java.net.URL;
import java.nio.file.Path;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;

@Getter
public class Fields {
    private String stringValue;
    private char primitiveCharacterValue;
    private Character characterValue;
    private int primitiveIntegerValue;
    private Integer integerValue;
    private long primitiveLongValue;
    private Long longValue;
    private double primitiveDoubleValue;
    private Double doubleValue;
    private boolean primitiveBooleanValue;
    private Boolean booleanValue;
    private BigDecimal bigDecimal;
    private UUID uuid;
    private Optional<Integer> optionalInteger;
    private Optional<String> optionalString;
    private LocalDate localDate;
    private LocalDateTime localDateTime;
    private ZonedDateTime zonedDateTime;
    private Instant instant;
    private List<String> listOfStrings;
    private Set<String> setOfStrings;
    private Map<Integer, String> mapOfIntegersToStrings;
    private Map<String, Integer> mapOfStringsToIntegers;
    private ArbitraryEnum arbitraryEnum;
    private String[] arrayOfStrings;
    private ArrayList<String> arrayList;
    private HashMap<String, String> hashMap;
    private HashSet<String> hashSet;
    private Date date;
    private Byte byteValue;
    private byte primitiveByteValue;
    private Short shortValue;
    private short primitiveShortValue;
    private Float floatValue;
    private float primitiveFloatValue;
    private LocalTime localTime;
    private BigInteger bigInteger;
    private OffsetDateTime offsetDateTime;
    private OffsetTime offsetTime;
    private Duration duration;
    private Period period;
    private java.sql.Date sqlDate;
    private Time sqlTime;
    private Timestamp sqlTimestamp;
    private Currency currency;
    private Locale locale;
    private TimeZone timeZone;
    private ZoneId zoneId;
    private ZoneOffset zoneOffset;
    private Year year;
    private YearMonth yearMonth;
    private MonthDay monthDay;
    private File file;
    private Path path;
    private URL url;
    private URI uri;
}
